Diploma/Pages/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Diploma.Models;
using Microsoft.AspNetCore.Identity;
using Diploma.ViewModels;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Data;
using System.Web;
using Microsoft.Extensions.Options;
using Newtonsoft.Json.Linq;
using Microsoft.Extensions.FileSystemGlobbing.Internal;
using System.Text.RegularExpressions;
using System.Threading.Tasks.Dataflow;
using System;
using Microsoft.Net.Http.Headers;
using Microsoft.AspNetCore.Http;
using System.Text.Json.Nodes;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.Differencing;

namespace Diploma.Pages
{
    public record class CameraTmp(Camera Camera, List<SelectListItem>? Selects);

    public record class UserTmp(IdentityUserDTO User, List<SelectListItem>? Selects);

    public class EditModel : PageModel
    {
        private class Element
        {
            public string? name { get; set; }
            public string? value { get; set; }
        }

        private DBContext _dbContext;

        //[BindProperty]
        //public _PersonViewModel PersonViewModel {get;set;}
        [BindProperty]
        public Area RoomModel { get; set; }

        [BindProperty]
        public List<Person> PersonList 
        { 
            get
            {
                return _dbContext.Persons.ToList();
            }
            private set { }

        }

        [BindProperty]
        public List<CameraDTO> CameraList
        {
            get
            {
                List<CameraDTO> dtoCameras = new List<CameraDTO>();
                List<Camera> cameras = _dbContext.Cameras.ToList();
                foreach (Camera cam in cameras)
                {
                    CameraDTO cameraDTO = new CameraDTO
                    {
                        Id = cam.Id,
                        Name = cam.Name,
                        Description = cam.Description,
                        AreaName = _dbContext.Areas.Where(x => x.Id == cam.AreaId).Select(x => x.Name).FirstOrDefault()
                    };
                    dtoCameras.Add(cameraDTO);
                }
                return dtoCameras;
            }
            private set { }

        }

        [BindProperty]
        public List<Area> AreaList
        {
            get
            {
                return _dbContext.Areas.ToList();
            }
            private set { }

        }

        [BindProperty]
        public List<IdentityUserDTO> UserList
        {
            get
            {
                List<IdentityUser> userList = _dbContext.Users.ToList();
                List<IdentityUserDTO> dtoList = new List<IdentityUserDTO>();
                foreach (IdentityUser user in userList)
                {
                    string roleId = _dbContext.UserRoles.Where(x => x.UserId == user.Id).Select(x => x.RoleId).FirstOrDefault();
                    dtoList.Add(new IdentityUserDTO()
                    {
                        Id=user.Id,
                        AccessFailedCount = user.AccessFailedCount,
                        Email = user.Email,
                        UserName = user.UserName,
                        PhoneNumber = user.PhoneNumber,
                        Role = _dbContext.Roles.Where(x => x.Id == roleId).Select(x=>x.Name).FirstOrDefault()

                    });
                }
                return dtoList;
            }
            private set { }

        }

        public EditModel(DBContext dBContext)    
        {
            _dbContext = dBContext;
            //PersonViewModel = new PersonViewModel();
        }

        public PartialViewResult OnGetUserListPartial()
        {
            return new PartialViewResult
            {
                ViewName = "_UserListPartial",
                ViewData = new ViewDataDictionary<List<IdentityUserDTO>>(ViewData, UserList)
            };
        }

        public PartialViewResult OnGetUserCreateOrEdit(string id)
        {
            List<SelectListItem> roles = _dbContext.Roles.Select(a => new SelectListItem { Value = a.Id, Text = a.Name }).ToList();

            return new PartialViewResult
            {
                ViewName = "_UserModalPartial",
                ViewData = new ViewDataDictionary<UserTmp>(ViewData,
                        new UserTmp(UserList.Where(x=>x.Id==id).FirstOrDefault(), roles))
            };
        }

        public PartialViewResult OnPostUserCreateOrEdit(string id, string role)
        {
            var q = from u in _dbContext.UserRoles
                    where u.UserId == id
                    select u;
            if (q.Count() > 0)
            {
                IdentityUserRole<string> iUser = q.First();
                _dbContext.UserRoles.Remove(iUser);
                _dbContext.SaveChanges();
                _dbContext.UserRoles.Add(new IdentityUserRole<string>()
                {
                    RoleId = role,
                    UserId = id
                });

            }
            else
            {
                _dbContext.UserRoles.Add(new IdentityUserRole<string>()
                {
                    RoleId = role,
                    UserId = id
                });
            }

            _dbContext.SaveChanges();
            return new PartialViewResult
            {
                ViewName = "_UserListPartial",
                ViewData = new ViewDataDictionary<List<IdentityUserDTO>>(ViewData, UserList)
            };
        }


        #region AreaOperations
        public PartialViewResult OnGetAreaDelete(int id)
        {
            return new PartialViewResult
            {
                ViewName = "_AreaDeleteWarningPartial",
                ViewData = new ViewDataDictionary<int>(ViewData, id)
            };
        }

        public async Task<PartialViewResult> OnPostAreaDelete(int id)
        {
            Area area = await _dbContext.Areas.Where(x => x.Id == id).FirstOrDefaultAsync();

            if (area != null)
            {
                _dbContext.Remove(area);
                await _dbContext.SaveChangesAsync();

            }
            return new PartialViewResult
            {
                ViewName = "_AreaListPartial",
                ViewData = new ViewDataDictionary<List<Area>>(ViewData, AreaList)
            };

        }

        public async Task<PartialViewResult> OnGetAreaCreateOrEdit(int id = 0)
        {
            if (id == 0)
            {
                return new PartialViewResult
                {
                    ViewName = "_AreaModalPartial",
                    ViewData = new ViewDataDictionary<Area>(ViewData, new Area())
                };
            }
            else
            {
                Area area = await _dbContext.Areas.Where(x => x.Id == id).FirstOrDefaultAsync();
                return new PartialViewResult
                {
                    ViewName = "_AreaModalPartial",
                    ViewData = new ViewDataDictionary<Area>(ViewData, area)
                };
            }
        }
        public async Task<PartialViewResult> OnPostAreaCreateOrEdit(int id, Area area)
        {
            if (ModelState.IsValid)
            {
                if (id == 0)
                {
                    await _dbContext.AddAsync(area);
                    await _dbContext.SaveChangesAsync();
                }
                else
                {
                    Area qArea = (from ar in _dbContext.Areas
                                  where ar.Id == id
                                  select ar).First();
                    qArea.Name = area.Name;
                    qArea.Description = area.Description;
                    qArea.Level = area.Level;

                    await _dbContext.SaveChangesAsync();
                }
                return new PartialViewResult
                {
                    ViewName = "_AreaListPartial",
                    ViewData = new ViewDataDictionary<List<Area>>(ViewData, AreaList)
                };
            }
            else
            {
                return new PartialViewResult
                {
                    ViewName = "_AreaModalPartial",
                    ViewData = new ViewDataDictionary<Area>(ViewData, area)
                };
            }
        }
        public PartialViewResult OnGetAreaListPartial()
        {
            return new PartialViewResult
            {
                ViewName = "_AreaListPartial",
                ViewData = new ViewDataDictionary<List<Area>>(ViewData, AreaList)
            };
        }
        #endregion



        #region CameraOperations



        public PartialViewResult OnGetCameraDelete(int id)
        {
            return new PartialViewResult
            {
                ViewName = "_CameraDeleteWarningPartial",
                ViewData = new ViewDataDictionary<int>(ViewData, id)
            };
        }

        public async Task<PartialViewResult> OnPostCameraDelete(int id)
        {
            Camera camera = await _dbContext.Cameras.Where(x=> x.Id == id).FirstOrDefaultAsync();

            if (camera != null) 
            {
                _dbContext.Remove(camera);
                await _dbContext.SaveChangesAsync();
                    
            }
            return new PartialViewResult
            {
                ViewName = "_CameraListPartial",
                ViewData = new ViewDataDictionary<List<CameraDTO>>(ViewData, CameraList)
            };

        }

        public async Task<PartialViewResult> OnGetCameraCreateOrEdit(int id = 0)
        {
            List<SelectListItem> areas = _dbContext.Areas.Select(a => new SelectListItem { Value = a.Id.ToString(), Text = a.Name }).ToList();
            if (id == 0)
            {
                return new PartialViewResult
                {
                    ViewName = "_CameraModalPartial",

Diploma/Pages/Roles.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using System.Data;

namespace Diploma.Pages
{
    [Authorize(Roles = "Admin")]
    public class RolesModel : PageModel
    {

        RoleManager<IdentityRole> roleManager;
        public List<IdentityRole> Roles { get; set; }

        public RolesModel(RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            Roles = roleManager.Roles.ToList();
            return Page();
        }

        //public PartialViewResult Index()
        //{
        //    var roles = roleManager.Roles.ToList();
        //    return new PartialViewResult
        //    {
        //        ViewName = "_RoleListPartial",
        //        ViewData = new ViewDataDictionary<List<IdentityRole>>(ViewData, roles)
        //    };
        //}
        public PartialViewResult OnGetCreate()
        {
            return new PartialViewResult
            {
                ViewName = "_RoleCreatePartial",
                ViewData = new ViewDataDictionary<IdentityRole>(ViewData, new IdentityRole())
            };
        }
        public async void OnPostCreate(IdentityRole role)
        {
            await roleManager.CreateAsync(role);
        }


        public async Task<IActionResult> Create(IdentityRole role)
        {
            await roleManager.CreateAsync(role);
            return RedirectToAction("Index");
        }
    }
}

Diploma/Pages/Shared/_AreaDeleteWarningPartial.cshtml
@model int

@*<div class="modal fade" id="add-contact" tabindex="-1" role="dialog" aria-labelledby="addContactLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content rounded-3 bg-black">
            <div class="modal-header">
                <h5 class="modal-title text-white" id="addContactLabel">Вы уверены что хотите удалить запись?</h5>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-listid="AreaListPartialView" data-handler="AreaListPartial" data-delete="modal" data-id="@Model" data-url="@Url.Page("Edit", "AreaModalDeletePartial")">
                    Удалить
                </button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
            </div>
        </div>
    </div>
</div>*@

<div class="modal-content rounded-3 bg-black">
    <div class="modal-body">
        <form asp-page-handler="AreaDelete" asp-route-id="@Model" method="post" onsubmit="return jQueryModalPost(this, 'AreaListPartialView');">
            <h5 class="text-white">Вы уверены что хотите удалить запись?</h5>

            <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
            <button type="submit" class="btn btn-danger save-button">Удлалить</button>
        </form>
    </div>
</div>

Diploma/Pages/Shared/_AreaListPartial.cshtml
@using Diploma.Models;

@model List<Area>
<table id="AreaGridPartialView" class="table table-borderless GridPartialView">
    <thead class="col text-center" style="text-align: center !important">
        <tr style="text-align: center !important">
            <th>
                <p class="text-white text-center">Название</p>
            </th>
            <th class="dt-center">
                <p class="text-white text-center">Описание</p>
            </th>
            <th class="dt-center">
                <p class="text-white text-center">Уровень</p>
            </th>
            <th class="dt-center">
                <p class="text-white text-center">Действия</p>
            </th>
        </tr>
    </thead>
    <tbody id="PersonListGridContent">
        @foreach(Area area in Model)
        {
            <tr >
                <td ><p class="text-white">@area.Name</p></td>
                <td><p class="text-white">@area.Description</p></td>
                <td><p class="text-white">@area.Level</p></td>
                <td>
                    <a onclick="jQueryModalGet('?handler=AreaCreateOrEdit&id=@area.Id','Редактировать')" class="btn btn-outline-light">
                        <i class="bi bi-pencil-square"></i>
                    </a>
                    @if (User.IsInRole("Admin"))
                    {
                        <a onclick="jQueryModalGet('?handler=AreaDelete&id=@area.Id','Удалить')" class="btn btn-outline-light">
                            <i class="bi bi-x-lg"></i>
                        </a>
                    }
                    

                    @*<button type="button" class="btn btn-outline-danger" data-handler="AreaListPartial" data-toggle="ajax-modal-delete-person" data-id="@area.Id" data-url="@Url.Page("Edit", "AreaModalDeletePartial")">
                        Удалить
                    </button>
                    <button type="button" class="btn btn-outline-danger" data-handler="AreaListPartial" data-toggle="ajax-modal-edit-person" data-id="@area.Id" data-url="@Url.Page("Edit", "AreaModalEditPartial")">
                        Редактировать
                    </button>*@
                </td>
            </tr>
        }
    </tbody>
</table>
<script>
    
    var table = $("#AreaGridPartialView").DataTable({
        stateSave: true,
        //language: {
        //    url: "//cdn.datatables.net/plug-ins/1.13.4/i18n/ru.json",
        //},
        "oLanguage": {
            "oPaginate": {
                //"sFirst": '<span class="pagination-default"><<</span><span class="pagination-fa"><i class="fa fa-chevron-right" ></i></span>',
                "sFirst": '<span class="pagination-default"><i class="bi bi-skip-start-fill"></i></span>',
                "sNext": '<span class="pagination-default"><i class="bi bi-caret-right-fill"></i></span>',
                "sPrevious": '<span class="pagination-default"><i class="bi bi-caret-left-fill"></i></span>',
                "sLast": '<span class="pagination-default"><i class="bi bi-skip-end-fill"></i></span>',

            },
            "oAria": {
                "sSortAscending": " - click/return to sort ascending"
            },

            "sLengthMenu": "Отобразить _MENU_ записей",
            "sInfo": "<p class='s-info-text'>Получено всего _TOTAL_ записей, показывается от (_START_ до _END_)<p>",

            "sSearch": "Поиск записи:",
        },
        "autoWidth": true,
        //language: {
        //    url: "//cdn.datatables.net/plug-ins/1.13.4/i18n/ru.json",
        //},
        scrollY: '45vh',
        "scrollCollapse": true,
        "paging": true,
        pagingType: "full_numbers",
        lengthMenu: [5, 10, 20, 50, 100, 200, 500],
        className: 'dt-center', targets: '_all'
    });


</script>

Diploma/Pages/Shared/_AreaModalPartial.cshtml
@using Diploma.Models;

@*// Pages/Shared/_PersonModalPartial.cshtml*@
@model Area
<!-- Modal -->

<div class="modal-content rounded-3 bg-black">
    <div class="modal-body">
        <form asp-page-handler="AreaCreateOrEdit" asp-route-id="@Model.Id" method="post" onsubmit="return jQueryModalPost(this, 'AreaListPartialView');">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
            <input asp-for="Id" class="form-control" type="hidden">
            <div class="row mb-3">
                <div class="col-lg-6">
                    <div class="form-floating mb-3">
                        <input asp-for="Name" class="form-control" placeholder=" ">
                        <label asp-for="Name" for="floatingInput">Наименование</label>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-floating mb-3">
                        <input asp-for="Description" class="form-control" placeholder=" " />
                        <label asp-for="Description" for="floatingInput">Описание</label>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="row mb-3">
                <div class="col-lg-6">
                    <div class="form-floating mb-3">
                        <input asp-for="Level" type="number" class="form-control" placeholder=" " />
                        <label asp-for="Level" for="floatingInput">Уровень</label>
                        <span asp-validation-for="Level" class="text-danger"></span>
                    </div>
                    @*<label asp-for="Area" class="col-form-label text-white"></label>
                    <select asp-for="Area" class="form-select" aria-label="Default select example" id="SubCategoryMenu">
                    @*<option value="1">One</option>
                    <option value="2">Two</option>
                    <option value="3">Three</option>*@
                    @*</select>*@

                </div>
            </div>

            <div class="modal-footer">
                @*<button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>*@
                @*<button type="button" class="btn btn-secondary close-button" data-dismiss="modal">Отмена</button>*@
                <button type="submit" class="btn btn-primary save-button">Сохранить</button>
            </div>
        </form>
    </div>
    @*<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
    <button type="button" class="btn btn-primary" data-listid="AreaListPartialView" data-handler="AreaListPartial" data-save="modal">Сохранить</button>
    </div>*@
    
</div>

<script type="text/javascript" language=javascript>
    $.validator.unobtrusive.parse(document);
</script>

Diploma/Pages/Shared/_CameraDeleteWarningPartial.cshtml
@model int


<div class="modal-content rounded-3 bg-black">
    <div class="modal-body">
        <form asp-page-handler="CameraDelete" asp-route-id="@Model" method="post" onsubmit="return jQueryModalPost(this, 'CameraListPartialView');">
            <h5 class="text-white">Вы уверены что хотите удалить запись?</h5>

            <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
            <button type="submit" class="btn btn-danger save-button">Удлалить</button>
        </form>
    </div>
</div>

Diploma/Pages/Shared/_CameraListPartial.cshtml
@using Diploma.ViewModels;

@model List<CameraDTO>

<table id="GridPartialView" class="table table-borderless GridPartialView">
    <thead>
        <tr style="justify-content: center">
            <th>
                <p class="text-white text-center">Имя</p>
            </th>
            <th>
                <p class="text-white text-center">Область</p>
            </th>
            <th>
                <p class="text-white text-center">Описание</p>
            </th>
            <th>
                <p class="text-white text-center">Действия</p>
            </th>
        </tr>
    </thead>
    <tbody id="CameraListGridContent">
        @foreach (CameraDTO cam in Model)
        {
            <tr>
                <td><p class="text-white">@cam.Name</p></td>
                <td><p class="text-white">@cam.AreaName</p></td>
                <td><p class="text-white">@cam.Description</p></td>
                <td>
                    <a onclick="jQueryModalGet('?handler=CameraCreateOrEdit&id=@cam.Id','Редактировать')" class="btn btn-outline-light">
                        <i class="bi bi-pencil-square"></i>
                    </a>
                    @if (User.IsInRole("Admin"))
                    {
                        <a onclick="jQueryModalGet('?handler=CameraDelete&id=@cam.Id','Удалить')" class="btn btn-outline-light">
                            <i class="bi bi-x-lg"></i>
                        </a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>
@*</div>*@

<script>
    $("#GridPartialView").DataTable({
        stateSave: true,
        //language: {
        //    url: "//cdn.datatables.net/plug-ins/1.13.4/i18n/ru.json",
        //},
        "oLanguage": {
            "oPaginate": {
                //"sFirst": '<span class="pagination-default"><<</span><span class="pagination-fa"><i class="fa fa-chevron-right" ></i></span>',
                "sFirst": '<span class="pagination-default"><i class="bi bi-skip-start-fill"></i></span>',
                "sNext": '<span class="pagination-default"><i class="bi bi-caret-right-fill"></i></span>',
                "sPrevious": '<span class="pagination-default"><i class="bi bi-caret-left-fill"></i></span>',
                "sLast": '<span class="pagination-default"><i class="bi bi-skip-end-fill"></i></span>',

            },
            "oAria": {
                "sSortAscending": " - click/return to sort ascending"
            },

            "sLengthMenu": "Отобразить _MENU_ записей",
            "sInfo": "<p class='s-info-text'>Получено всего _TOTAL_ записей, показывается от (_START_ до _END_)<p>",

            "sSearch": "Поиск записи:",
        },
        //language: {
        //    url: "//cdn.datatables.net/plug-ins/1.13.4/i18n/ru.json",
        //},
        scrollY: '45vh',
        "scrollCollapse": true,
        "paging": true,
        pagingType: "full_numbers",
        lengthMenu: [5, 10, 20, 50, 100, 200, 500],
    });
</script>

Diploma/Pages/Shared/_CameraModalPartial.cshtml
@using Diploma.Models;

@*// Pages/Shared/_PersonModalPartial.cshtml*@
@model CameraTmp
<!-- Modal -->
@*<div class="modal fade" id="add-contact" tabindex="-1" role="dialog" aria-labelledby="addContactLabel" aria-hidden="true" style="backdrop-filter: blur(0.6rem);  box-shadow: 1.3rem 1.3rem 1.3rem rgba(0,0,0,0.5); background-color: rgba(255,255,255,0.05) !important;">*@
@*<div class="modal-dialog" role="document">*@
<div class="modal-content rounded-3 bg-black">
    <div class="modal-body">
        <form asp-page-handler="CameraCreateOrEdit" asp-route-id="@Model.Camera.Id" method="post" onsubmit="return jQueryModalPost(this, 'CameraListPartialView');">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
            <input asp-for="Camera.Id" class="form-control" type="hidden">

            <div class="row mb-3">
                <div class="col-lg-6">
                    <div class="form-floating mb-3">
                        <input asp-for="Camera.Name" class="form-control" placeholder="Тест камера">
                        <label asp-for="Camera.Name" for="floatingInput"></label>
                        <span asp-validation-for="Camera.Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-floating mb-3">
                        <input asp-for="Camera.Description" class="form-control" placeholder=" ">
                        <label asp-for="Camera.Description" for="floatingInput"></label>
                        <span asp-validation-for="Camera.Description" class="text-danger"></span>
                    </div>
                    
                </div>
            </div>

            <div class="row mb-3">
                <div class="col-lg-6">
                    <span asp-validation-for="Camera.AreaId" class="text-danger"></span>
                    <div class="form-floating mb-3">
                        <select asp-for="Camera.AreaId" asp-items="Model.Selects" class="form-select"></select>
                        <label asp-for="Camera.AreaId" class="form-label">Помещение</label>
                    </div>
                </div>
            </div>
            @*<div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
            <button type="button" class="btn btn-primary" data-listid="CameraListPartialView" data-handler="CameraListPartial" data-save="modal">Сохранить</button>
            </div>*@
            <div class="modal-footer">
                @*<button type="button" class="btn btn-secondary close-button" data-dismiss="modal">Отмена</button>*@
                <button type="submit" class="btn btn-primary save-button">Сохранить</button>
            </div>
        </form>
    </div>

</div>
<script type="text/javascript" language=javascript>
    $.validator.unobtrusive.parse(document);
</script>

Diploma/Pages/Shared/_PersonDeleteWarningPartial.cshtml
@model int

@*<div class="modal fade" id="add-contact" tabindex="-1" role="dialog" aria-labelledby="addContactLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content rounded-3 bg-black">
            <div class="modal-header">
                <h5 class="modal-title text-white" id="addContactLabel">Вы уверены что хотите удалить запись?</h5>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-listid="PersonListPartialView" data-handler="PersonListPartial" data-delete="modal" data-id="@Model" data-url="@Url.Page("Edit", "PersonModalDeletePartial")">
                    Удалить
                </button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
            </div>
        </div>
    </div>
</div>*@

<div class="modal-content rounded-3 bg-black">
    <div class="modal-body">
        <form asp-page-handler="PersonDelete" asp-route-id="@Model" method="post" onsubmit="return jQueryModalPost(this, 'PersonListPartialView');">
            <h5 class="text-white">Вы уверены что хотите удалить запись?</h5>

            <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
            <button type="submit" class="btn btn-danger save-button">Удлалить</button>
        </form>
    </div>
</div>

Diploma/Pages/Shared/_RoleCreatePartial.cshtml
@page
@using Microsoft.AspNetCore.Identity;
@Html.AntiForgeryToken()
@model IdentityRole
@{
}
<div class="modal-content rounded-3 bg-black">
    <div class="modal-body">
        <form asp-page-handler="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row mb-3">
                <div class="col-lg-6">
                    <div class="form-floating mb-3">
                        <input asp-for="Name" class="form-control" placeholder=" ">
                        <label asp-for="Name" for="floatingInput"></label>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="modal-footer">
                @*<button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>*@
                @*<button type="button" class="btn btn-secondary close-button" data-dismiss="modal">Отмена</button>*@
                <button type="submit" class="btn btn-primary save-button">Сохранить</button>
            </div>
        </form>
    </div>
    @*<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
    <button type="button" class="btn btn-primary" data-listid="AreaListPartialView" data-handler="AreaListPartial" data-save="modal">Сохранить</button>
    </div>*@

</div>

Diploma/Pages/Shared/_UserModalPartial.cshtml
@using Diploma.Models;
@using Diploma.ViewModels;

@*// Pages/Shared/_PersonModalPartial.cshtml*@
@model UserTmp
<!-- Modal -->

<div class="modal-content rounded-3 bg-black">
    <div class="modal-body">
        <form asp-page-handler="UserCreateOrEdit" asp-route-id="@Model.User.Id" method="post" onsubmit="return jQueryModalPostUser('UserListPartialView');">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
            <input asp-for="User.Id" class="form-control" type="hidden" id="id-user-input">
            <div class="row mb-3">
                <div class="col-lg-6">
                    <div class="form-floating mb-3">
                        <input asp-for="User.UserName" class="form-control" placeholder=" " readonly>
                        <label asp-for="User.UserName" for="floatingInput"></label>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-floating mb-3">
                        <select asp-for="User.Role" asp-items="Model.Selects" class="form-select" id="select-role-user"></select> @*asp-items="Model.Selects"*@
                        <label asp-for="User.Role" class="form-label">Роль</label>
                    </div>
                </div>
            </div>

            <div class="modal-footer">
                <button type="submit" class="btn btn-primary save-button">Сохранить</button>
            </div>
        </form>
    </div>
    
</div>

<script type="text/javascript" language=javascript>
    $.validator.unobtrusive.parse(document);
</script>