Diploma/Pages/ConfigurationSettings.cshtml.cs
using Diploma.Models;
using Diploma.Controllers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Diploma.Pages
{
    public class ConfigurationSettingsModel : PageModel
    {
        public ProjectConfiguration ProjectConfiguration { get; set; }

        private Controllers.ConfigurationManager _configurationManager { get; set; }

        public ConfigurationSettingsModel() {
            _configurationManager = new Controllers.ConfigurationManager(@"Files/startup_config.json");
        }

        public IActionResult OnGet()
        {
            ProjectConfiguration = _configurationManager.Config;
            
            return Page();
        }
    }
}

Diploma/Pages/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Diploma.Models;
using Microsoft.AspNetCore.Identity;
using Diploma.ViewModels;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Data;
using System.Web;
using Microsoft.Extensions.Options;
using Newtonsoft.Json.Linq;
using Microsoft.Extensions.FileSystemGlobbing.Internal;
using System.Text.RegularExpressions;
using System.Threading.Tasks.Dataflow;
using System;
using Microsoft.Net.Http.Headers;
using Microsoft.AspNetCore.Http;
using System.Text.Json.Nodes;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.Differencing;

namespace Diploma.Pages
{
    public record class CameraTmp(Camera Camera, List<SelectListItem>? Selects);

    public record class UserTmp(IdentityUserDTO User, List<SelectListItem>? Selects);

    public class EditModel : PageModel
    {
        private class Element
        {
            public string? name { get; set; }
            public string? value { get; set; }
        }

        private DBContext _dbContext;

        //[BindProperty]
        //public _PersonViewModel PersonViewModel {get;set;}
        [BindProperty]
        public Area RoomModel { get; set; }

        [BindProperty]
        public List<Person> PersonList 
        { 
            get
            {
                return _dbContext.Persons.ToList();
            }
            private set { }

        }

        [BindProperty]
        public List<CameraDTO> CameraList
        {
            get
            {
                List<CameraDTO> dtoCameras = new List<CameraDTO>();
                List<Camera> cameras = _dbContext.Cameras.ToList();
                foreach (Camera cam in cameras)
                {
                    CameraDTO cameraDTO = new CameraDTO
                    {
                        Id = cam.Id,
                        Name = cam.Name,
                        Description = cam.Description,
                        AreaName = _dbContext.Areas.Where(x => x.Id == cam.AreaId).Select(x => x.Name).FirstOrDefault()
                    };
                    dtoCameras.Add(cameraDTO);
                }
                return dtoCameras;
            }
            private set { }

        }

        [BindProperty]
        public List<Area> AreaList
        {
            get
            {
                return _dbContext.Areas.ToList();
            }
            private set { }

        }

        [BindProperty]
        public List<IdentityUserDTO> UserList
        {
            get
            {
                List<IdentityUser> userList = _dbContext.Users.ToList();
                List<IdentityUserDTO> dtoList = new List<IdentityUserDTO>();
                foreach (IdentityUser user in userList)
                {
                    string roleId = _dbContext.UserRoles.Where(x => x.UserId == user.Id).Select(x => x.RoleId).FirstOrDefault();
                    dtoList.Add(new IdentityUserDTO()
                    {
                        Id=user.Id,
                        AccessFailedCount = user.AccessFailedCount,
                        Email = user.Email,
                        UserName = user.UserName,
                        PhoneNumber = user.PhoneNumber,
                        Role = _dbContext.Roles.Where(x => x.Id == roleId).Select(x=>x.Name).FirstOrDefault()

                    });
                }
                return dtoList;
            }
            private set { }

        }

        public EditModel(DBContext dBContext)    
        {
            _dbContext = dBContext;
            //PersonViewModel = new PersonViewModel();
        }

        public PartialViewResult OnGetUserListPartial()
        {
            return new PartialViewResult
            {
                ViewName = "_UserListPartial",
                ViewData = new ViewDataDictionary<List<IdentityUserDTO>>(ViewData, UserList)
            };
        }

        public PartialViewResult OnGetUserCreateOrEdit(string id)
        {
            List<SelectListItem> roles = _dbContext.Roles.Select(a => new SelectListItem { Value = a.Id, Text = a.Name }).ToList();

            return new PartialViewResult
            {
                ViewName = "_UserModalPartial",
                ViewData = new ViewDataDictionary<UserTmp>(ViewData,
                        new UserTmp(UserList.Where(x=>x.Id==id).FirstOrDefault(), roles))
            };
        }

        public PartialViewResult OnPostUserCreateOrEdit(string id, string role)
        {
            var q = from u in _dbContext.UserRoles
                    where u.UserId == id
                    select u;
            if (q.Count() > 0)
            {
                IdentityUserRole<string> iUser = q.First();
                _dbContext.UserRoles.Remove(iUser);
                _dbContext.SaveChanges();
                _dbContext.UserRoles.Add(new IdentityUserRole<string>()
                {
                    RoleId = role,
                    UserId = id
                });

            }
            else
            {
                _dbContext.UserRoles.Add(new IdentityUserRole<string>()
                {
                    RoleId = role,
                    UserId = id
                });
            }

            _dbContext.SaveChanges();
            return new PartialViewResult
            {
                ViewName = "_UserListPartial",
                ViewData = new ViewDataDictionary<List<IdentityUserDTO>>(ViewData, UserList)
            };
        }


        #region AreaOperations
        public PartialViewResult OnGetAreaDelete(int id)
        {
            return new PartialViewResult
            {
                ViewName = "_AreaDeleteWarningPartial",
                ViewData = new ViewDataDictionary<int>(ViewData, id)
            };
        }

        public async Task<PartialViewResult> OnPostAreaDelete(int id)
        {
            Area area = await _dbContext.Areas.Where(x => x.Id == id).FirstOrDefaultAsync();

            if (area != null)
            {
                _dbContext.Remove(area);
                await _dbContext.SaveChangesAsync();

            }
            return new PartialViewResult
            {
                ViewName = "_AreaListPartial",
                ViewData = new ViewDataDictionary<List<Area>>(ViewData, AreaList)
            };

        }

        public async Task<PartialViewResult> OnGetAreaCreateOrEdit(int id = 0)
        {
            if (id == 0)
            {
                return new PartialViewResult
                {
                    ViewName = "_AreaModalPartial",
                    ViewData = new ViewDataDictionary<Area>(ViewData, new Area())
                };
            }
            else
            {
                Area area = await _dbContext.Areas.Where(x => x.Id == id).FirstOrDefaultAsync();
                return new PartialViewResult
                {
                    ViewName = "_AreaModalPartial",
                    ViewData = new ViewDataDictionary<Area>(ViewData, area)
                };
            }
        }
        public async Task<PartialViewResult> OnPostAreaCreateOrEdit(int id, Area area)
        {
            if (ModelState.IsValid)
            {
                if (id == 0)
                {
                    await _dbContext.AddAsync(area);
                    await _dbContext.SaveChangesAsync();
                }
                else
                {
                    Area qArea = (from ar in _dbContext.Areas
                                  where ar.Id == id
                                  select ar).First();
                    qArea.Name = area.Name;
                    qArea.Description = area.Description;
                    qArea.Level = area.Level;

                    await _dbContext.SaveChangesAsync();
                }
                return new PartialViewResult
                {
                    ViewName = "_AreaListPartial",
                    ViewData = new ViewDataDictionary<List<Area>>(ViewData, AreaList)
                };
            }
            else
            {
                return new PartialViewResult
                {
                    ViewName = "_AreaModalPartial",
                    ViewData = new ViewDataDictionary<Area>(ViewData, area)
                };
            }
        }
        public PartialViewResult OnGetAreaListPartial()
        {
            return new PartialViewResult
            {
                ViewName = "_AreaListPartial",
                ViewData = new ViewDataDictionary<List<Area>>(ViewData, AreaList)
            };
        }
        #endregion



        #region CameraOperations



        public PartialViewResult OnGetCameraDelete(int id)
        {
            return new PartialViewResult
            {
                ViewName = "_CameraDeleteWarningPartial",
                ViewData = new ViewDataDictionary<int>(ViewData, id)
            };
        }

        public async Task<PartialViewResult> OnPostCameraDelete(int id)
        {
            Camera camera = await _dbContext.Cameras.Where(x=> x.Id == id).FirstOrDefaultAsync();

            if (camera != null) 
            {
                _dbContext.Remove(camera);
                await _dbContext.SaveChangesAsync();
                    
            }
            return new PartialViewResult
            {
                ViewName = "_CameraListPartial",
                ViewData = new ViewDataDictionary<List<CameraDTO>>(ViewData, CameraList)
            };

        }

        public async Task<PartialViewResult> OnGetCameraCreateOrEdit(int id = 0)
        {
            List<SelectListItem> areas = _dbContext.Areas.Select(a => new SelectListItem { Value = a.Id.ToString(), Text = a.Name }).ToList();
            if (id == 0)
            {
                return new PartialViewResult
                {
                    ViewName = "_CameraModalPartial",

Diploma/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Diploma.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Diploma/Pages/Index.cshtml.cs
using Diploma.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Diploma.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger, DBContext dbContext)
        {
            _logger = logger;
            Console.WriteLine(dbContext.UserRoles.FirstOrDefault().RoleId + dbContext.UserRoles.FirstOrDefault().UserId);
        }

        public IActionResult OnGet()
        {

            return Page();
        }

    }
}

Diploma/Pages/Login.cshtml.cs
using Diploma.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Diploma.Pages
{
    public class LoginModel : PageModel
    {

        private readonly SignInManager<IdentityUser> signInManager;


        [BindProperty]
        public Login Model { get; set; }


        public LoginModel(SignInManager<IdentityUser> signInManager)
        {
            this.signInManager = signInManager;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost(string? returnUrl = null)
        {
            if (ModelState.IsValid)
            {
                var identityResult = await signInManager.PasswordSignInAsync(Model.Email, Model.Password, Model.RememberMe, false);
                if (identityResult.Succeeded)
                {
                    if(returnUrl == null || returnUrl == "/")
                    {
                        return RedirectToPage("Index");
                    }
                    else
                    {
                        return RedirectToPage(returnUrl);
                    }
                }
                ModelState.AddModelError("", "Username or password incorrect");
            }
            return Page();
        }
    }
}

Diploma/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Diploma.Pages
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<IdentityUser> signInManager;

        public LogoutModel(SignInManager<IdentityUser> signInManager)
        {
            this.signInManager = signInManager;
        }
        public void OnGet()
        {
        }
        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await signInManager.SignOutAsync();
            return RedirectToPage("Login");
        }
        public IActionResult OnPostDontLogoutAsync()
        {
            return RedirectToPage("Index");
        }
    }
}

Diploma/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using AspNetCoreHero.ToastNotification.Abstractions;

namespace Diploma.Pages
{
    [Authorize]
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Diploma/Pages/Register.cshtml.cs
using Diploma.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Diploma.Pages
{
    public class RegisterModel : PageModel
    {

        [BindProperty]
        public Register Model { get; set; }
        public UserManager<IdentityUser> UserManager { get; }
        public SignInManager<IdentityUser> SignInManager { get; }

        public RegisterModel(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var user = new IdentityUser { 
                    UserName = Model.Email,
                    Email = Model.Email 
                };

                var result = await UserManager.CreateAsync(user, password: Model.Password);
                if (result.Succeeded)
                {
                    await SignInManager.SignInAsync(user, isPersistent: false);
                    return RedirectToPage("Index");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return Page();
        }
    }
}

Diploma/Pages/Roles.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using System.Data;

namespace Diploma.Pages
{
    [Authorize(Roles = "Admin")]
    public class RolesModel : PageModel
    {

        RoleManager<IdentityRole> roleManager;
        public List<IdentityRole> Roles { get; set; }

        public RolesModel(RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            Roles = roleManager.Roles.ToList();
            return Page();
        }

        //public PartialViewResult Index()
        //{
        //    var roles = roleManager.Roles.ToList();
        //    return new PartialViewResult
        //    {
        //        ViewName = "_RoleListPartial",
        //        ViewData = new ViewDataDictionary<List<IdentityRole>>(ViewData, roles)
        //    };
        //}
        public PartialViewResult OnGetCreate()
        {
            return new PartialViewResult
            {
                ViewName = "_RoleCreatePartial",
                ViewData = new ViewDataDictionary<IdentityRole>(ViewData, new IdentityRole())
            };
        }
        public async void OnPostCreate(IdentityRole role)
        {
            await roleManager.CreateAsync(role);
        }


        public async Task<IActionResult> Create(IdentityRole role)
        {
            await roleManager.CreateAsync(role);
            return RedirectToAction("Index");
        }
    }
}

Diploma/Pages/ConfigurationSettings.cshtml
@page
@model Diploma.Pages.ConfigurationSettingsModel
@{
    
}

<h>Редактирование файла конфигурации</h>
<table class="table table-striped GridPartialView">
    <thead>
        <tr>
            <th>
                <p class="text-white">Id</p>
            </th>
            <th>
                <p class="text-white">Источник</p>
            </th>
        </tr>
    </thead>
    <tbody id="PersonListGridContent">
        @foreach (var (cam, source) in Model.ProjectConfiguration.Cameras.Zip(Model.ProjectConfiguration.Sources))
        {
            <tr>
                <td><p class="text-white">@cam</p></td>
                <td><p class="text-white">@source</p></td>

            </tr>
        }
    </tbody>
</table>

Diploma/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<!doctype html>
<html lang="en" data-bs-theme="dark">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Hello, world!</title>
    <!-- script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js"></!-->
    <script language="JavaScript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.0/jquery.min.js"></script>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- SignalR-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/6.0.1/signalr.js"></script>

    @* <script src="~/lib/bootstrap/dist/js/bs5-toast.js"></script>*@
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400&display=swap" rel="stylesheet">
    <script src="~/js/notify.js"></script>

    
</head>



<body style="font-family: 'Montserrat', sans-serif;">
    <div class="wrapper">
        <div class=" container-fluid text-center mb-lg-3">
            <div class="d-block" style="height: 50vh">
                @*<p class="fs-1 text-light" style="height: 50vh; border: solid 5px pink">МОНИТОРИНГ<br />средств индивидуальной защиты</p>*@
                <p style="height: 25%"></p>
                <p class="fs-1 text-light">МОНИТОРИНГ</p>
                <p class="fs-2 text-light">средств индивидуальной защиты</p>
               
            </div>
            @if (User.Identity.IsAuthenticated)
            {
                <div class="row">
                    <div class="col">
                        <div class="card bg-black border border-secondary shadow-lg" style="height: 14rem">
                            <div class="card-body">
                                <h5 class="card-title text-light">Просмотр логов</h5>
                                <p class="card-text text-light">Просмотр данных об обнаружениях, а также изобаржений и времени нахождения.</p>
                                
                                <a class="btn btn-primary border-0" asp-area="" asp-page="/Logs" style="border-radius: 10px; bottom:0!important">Просмотр</a>
                                
                            </div>
                        </div>
                    </div>

                    <div class="col">
                        <div class="card bg-black border border-secondary shadow-lg" style="height: 14rem;">
                            <div class=" card-body solid-card-style">
                                <h5 class="card-title text-light">Редактирование данных</h5>
                                <p class="card-text text-light">Позволяет редактировать данные камер, сотрудников и областей. Также просмотр данных пользователей для администраторов.</p>
                                <a class="btn btn-primary border-0" asp-area="" asp-page="/Edit" style="border-radius: 10px">Редактировать</a>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card bg-black border border-secondary shadow-lg" style="height: 14rem">
                            <div class="card-body">
                                <h5 class="card-title text-light">Загрузка изображений</h5>
                                <p class="card-text text-light">Удобная и быстрая загрузка нескольких изображений для каждого работника системы.</p>
                                <a class="btn btn-primary border-0" asp-area="" asp-page="/Upload" style="border-radius: 10px">Загрузить</a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>

    @*<form method="POST">
        <input type="text" name="product" />
        <input type="submit" asp-page-handler="Create" value="Отправить" />
    </form>*@
    <link rel="stylesheet" href="https://raw.githubusercontent.com/f3oall/awesome-notifications/master/dist/style.css">
    <script src="https://raw.githubusercontent.com/f3oall/awesome-notifications/master/dist/index.var.js"></script>
    <script>
        $(document).ready(function () {
            function test(){
                $.notify("Hello World");
            }
            
        });
    </script>
</body>
</html>

Diploma/Pages/Login.cshtml
@page
@model Diploma.Pages.LoginModel
@{
}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3  text-light"> Login</h1>
            <form method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="mb-3">
                    <label class="form-label text-light" asp-for="Model.Email">Email address</label>
                    <input type="text" asp-for="Model.Email" class="form-control"/>
                    <span asp-validation-for="Model.Email" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label text-light" asp-for="Model.Password">Password</label>
                    <input type="password" asp-for="Model.Password" class="form-control" type="password" />
                    <span asp-validation-for="Model.Password" class="text-danger"></span>
                </div>
                @*<div class="mb-3 form-check">
                    <input type="checkbox" asp-for="Model.RememberMe" class="form-check-label" />
                    <label class="form-check-label text-light" asp-for="Model.RememberMe">RememberMe</label>
                </div>*@
                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
            </form>
            
        </div>
    </div>
</div>

Diploma/Pages/Logout.cshtml
@page
@model Diploma.Pages.LogoutModel
@{
}

<form method="post">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-12 col-lg-4">
                <p class="text-white" >Are you sure you want to logout?</p>
                <p>
                    <button class="btn btn-danger" asp-page-handler="Logout">Yes</button>
                    <button class="btn btn-primary ml-5 border-dark" asp-page-handler="DontLogout">No</button>
                </p>
            </div>
        </div>
    </div>
</form>

Diploma/Pages/Logs.cshtml
@page
@model Diploma.Pages.LogsModel
@{
}

<div id="logList">

</div>

@section Scripts {
@*    <script src="~/js/site.js"></script>*@
    <script>
        $(document).ready(function () {
            $('#logList').load('?handler=LogListPartial');
        });

    </script>
    

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Diploma/Pages/Register.cshtml
@page
@model Diploma.Pages.RegisterModel
@{
}

<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3  text-light">Register</h1>

            <form method="post">
                <div asp-validation-summary="All" class="text-danger"></div>

                <div class="mb-3">
                    <label class="form-label  text-light" asp-for="Model.Email">Email Address</label>
                    <input class="form-control" asp-for="Model.Email" />
                    <span class="text-danger" asp-validation-for="Model.Email"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label  text-light" asp-for="Model.Password">Password</label>
                    <input class="form-control" asp-for="Model.Password" type="password"/>
                    <span class="text-danger" asp-validation-for="Model.Password"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label  text-light" asp-for="Model.ConfirmPassword">Confirm password</label>
                    <input class="form-control" asp-for="Model.ConfirmPassword" type="password" />
                    <span class="text-danger" asp-validation-for="Model.ConfirmPassword"></span>
                </div>

                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Register</button>
                </div>
            </form>
        </div>
    </div>
</div>

Diploma/Pages/Roles.cshtml
@page
@model Diploma.Pages.RolesModel
@{
}


<h1 class=" text-light">Список ролей</h1>
<div class="container">
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <td class=" text-light">Id</td>
                <td class=" text-light">Name</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var role in Model.Roles)
            {
                <tr>
                    <td class=" text-light">@role.Id</td>
                    <td class=" text-light">@role.Name</td>
                </tr>
            }
        </tbody>
    </table>
</div>