Diploma — копия/Pages/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Diploma.Models;
using Microsoft.AspNetCore.Identity;
using Diploma.ViewModels;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Data;
using System.Web;
using Microsoft.Extensions.Options;
using Newtonsoft.Json.Linq;
using Microsoft.Extensions.FileSystemGlobbing.Internal;
using System.Text.RegularExpressions;
using System.Threading.Tasks.Dataflow;
using System;
using Microsoft.Net.Http.Headers;
using Microsoft.AspNetCore.Http;
using System.Text.Json.Nodes;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Diploma.Pages
{
    
    public class EditModel : PageModel
    {
        private class Element
        {
            public string? name { get; set; }
            public string? value { get; set; }
        }

        private DBContext _dbContext;

        [BindProperty]
        public PersonViewModel PersonViewModel {get;set;}
        [BindProperty]
        public Area RoomModel { get; set; }

        [BindProperty]
        public List<Person> PersonList 
        { 
            get
            {
                return _dbContext.Persons.ToList();
            }
            private set { }

        }

        [BindProperty]
        public List<Camera> CameraList
        {
            get
            {
                return _dbContext.Cameras.ToList();
            }
            private set { }

        }

        [BindProperty]
        public List<Area> AreaList
        {
            get
            {
                return _dbContext.Areas.ToList();
            }
            private set { }

        }

        [BindProperty]
        public List<IdentityUser> UserList
        {
            get
            {
                return _dbContext.Users.ToList();
            }
            private set { }

        }

        public EditModel(DBContext dBContext)    
        {
            _dbContext = dBContext;
            PersonViewModel = new PersonViewModel();
        }



        #region AreaOperations

        public PartialViewResult OnGetAreaModalDeletePartial(int id)
        {
            return new PartialViewResult
            {
                ViewName = "_AreaDeleteWarningPartial",
                ViewData = new ViewDataDictionary<int>(ViewData, id)
            };
        }

        public async Task OnPostAreaModalDeletePartial(int id)
        {
            Area person = await _dbContext.Areas.Where(x => x.Id == id).FirstOrDefaultAsync();
            if (person != null)
            {
                Console.WriteLine("Deleted id: " + id.ToString());
                _dbContext.Areas.Remove(person);
            }
            await _dbContext.SaveChangesAsync();
        }


        public async Task<PartialViewResult> OnGetAreaModalEditPartial(int id)
        {
            Area model = await _dbContext.Areas.Where(x => x.Id == id).FirstOrDefaultAsync();

            return new PartialViewResult
            {
                ViewName = "_AreaModalPartial",
                ViewData = new ViewDataDictionary<Area>(ViewData, model)
            };
        }

        public PartialViewResult OnGetAreaModalPartial()
        {
            return new PartialViewResult
            {
                ViewName = "_AreaModalPartial",
                ViewData = new ViewDataDictionary<Area>(ViewData, new Area { })
            };
        }


        public async Task<PartialViewResult> OnPostAreaModalPartial(Area model)
        {
            if (ModelState.IsValid)
            {
                Console.WriteLine(model.Id);
                if (model.Id != 0)
                {
                    Area camera = await _dbContext.Areas.Where(x => x.Id == model.Id).FirstOrDefaultAsync();
                    if (camera != null)
                    {
                        _dbContext.Areas.Remove(camera);
                        await _dbContext.Areas.AddAsync(model);
                    }
                }
                else
                {
                    await _dbContext.Areas.AddAsync(model);
                }

                await _dbContext.SaveChangesAsync();
            }

            return new PartialViewResult
            {
                ViewName = "_AreaModalPartial",
                ViewData = new ViewDataDictionary<Area>(ViewData, model)
            };
        }

        public PartialViewResult OnGetAreaListPartial()
        {
            return new PartialViewResult
            {
                ViewName = "_AreaListPartial",
                ViewData = new ViewDataDictionary<List<Area>>(ViewData, AreaList)
            };
        }
        #endregion

        #region CameraOperations

        public JsonResult OnGetAreas()
        {
            List<Area> areaList = _dbContext.Areas.ToList();
            return new JsonResult(areaList);

        }

        public PartialViewResult OnGetCameraModalDeletePartial(int id)
        {
            return new PartialViewResult
            {
                ViewName = "_CameraDeleteWarningPartial",
                ViewData = new ViewDataDictionary<int>(ViewData, id)
            };
        }

        public async Task OnPostCameraModalDeletePartial(int id)
        {
            Camera person = await _dbContext.Cameras.Where(x => x.Id == id).FirstOrDefaultAsync();
            if (person != null)
            {
                Console.WriteLine("Deleted id: " + id.ToString());
                _dbContext.Cameras.Remove(person);
            }
            await _dbContext.SaveChangesAsync();
        }


        public async Task<PartialViewResult> OnGetCameraModalEditPartial(int id)
        {
            Camera model = await _dbContext.Cameras.Where(x => x.Id == id).FirstOrDefaultAsync();

            return new PartialViewResult
            {
                ViewName = "_CameraModalPartial",
                ViewData = new ViewDataDictionary<Camera>(ViewData, model)
            };
        }

        public PartialViewResult OnGetCameraModalPartial()
        {
            return new PartialViewResult
            {
                ViewName = "_CameraModalPartial",
                ViewData = new ViewDataDictionary<Camera>(ViewData, new Camera { })
            };
        }


        public async Task<PartialViewResult> OnPostCameraModalPartial(Camera model)
        {
            if (ModelState.IsValid)
            {
                Console.WriteLine(model.Id);
                if (model.Id != 0)
                {
                    Camera camera = await _dbContext.Cameras.Where(x => x.Id == model.Id).FirstOrDefaultAsync();
                    if (camera != null)
                    {
                        _dbContext.Cameras.Remove(camera);
                        await _dbContext.Cameras.AddAsync(model);
                    }
                }
                else
                {
                    await _dbContext.Cameras.AddAsync(model);
                }

                await _dbContext.SaveChangesAsync();
            }

            return new PartialViewResult
            {
                ViewName = "_CameraModalPartial",
                ViewData = new ViewDataDictionary<Camera>(ViewData, model)
            };
        }

        public PartialViewResult OnGetCameraListPartial()
        {
            return new PartialViewResult
            {
                ViewName = "_CameraListPartial",
                ViewData = new ViewDataDictionary<List<Camera>>(ViewData, CameraList)
            };
        }
        #endregion


        #region PersonOperations
        public PartialViewResult OnGetPersonModalDeletePartial(int id)
        {
            return new PartialViewResult
            {
                ViewName = "_PersonDeleteWarningPartial",
                ViewData = new ViewDataDictionary<int>(ViewData, id)
            };
        }

        public async Task OnPostPersonModalDeletePartial(int id)
        {
            Person person = await _dbContext.Persons.Where(x => x.Id == id).FirstOrDefaultAsync();
            if (person != null)
            {
                Console.WriteLine("Deleted id: " + id.ToString());
                _dbContext.Persons.Remove(person);
            }
            await _dbContext.SaveChangesAsync();
        }


        public async Task<PartialViewResult> OnGetPersonModalEditPartial(int id)
        {
            Person model = await _dbContext.Persons.Where(x => x.Id == id).FirstOrDefaultAsync();

            return new PartialViewResult
            {
                ViewName = "_PersonModalPartial",
                ViewData = new ViewDataDictionary<Person>(ViewData, model)
            };
        }

        public PartialViewResult OnGetPersonModalPartial()
        {
            Console.WriteLine("44444");
            return new PartialViewResult
            {
                ViewName = "_PersonModalPartial",
                ViewData = new ViewDataDictionary<Person>(ViewData, new Person { })
            };
        }


        public async Task<PartialViewResult> OnPostPersonModalPartial(Person model)
        {
            if (ModelState.IsValid)
            {
                Console.WriteLine(model.Id);
                if (model.Id != 0)
                {
                    Person person = await _dbContext.Persons.Where(x => x.Id == model.Id).FirstOrDefaultAsync();
                    if (person != null)
                    {
                        _dbContext.Persons.Remove(person);
                        await _dbContext.Persons.AddAsync(model);
                    }
                }
                else
                {
                    await _dbContext.Persons.AddAsync(model);
                }
                
                await _dbContext.SaveChangesAsync();
            }

            return new PartialViewResult
            {
                ViewName = "_PersonModalPartial",

Diploma — копия/Pages/Shared/_AreaDeleteWarningPartial.cshtml
@model int

<div class="modal fade" id="add-contact" tabindex="-1" role="dialog" aria-labelledby="addContactLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content rounded-3 bg-black">
            <div class="modal-header">
                <h5 class="modal-title text-white" id="addContactLabel">Вы уверены что хотите удалить запись?</h5>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-listid="AreaListPartialView" data-handler="AreaListPartial" data-delete="modal" data-id="@Model" data-url="@Url.Page("Edit", "AreaModalDeletePartial")">
                    Удалить
                </button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
            </div>
        </div>
    </div>
</div>

Diploma — копия/Pages/Shared/_AreaListPartial.cshtml
@using Diploma.Models;

@model List<Area>

<table id="GridPartialView" class="table table-striped GridPartialView">
    <thead>
        <tr>
            <th> 
                <p class="text-white">Название</p>
            </th>
            <th> 
                <p class="text-white">Описание</p>
            </th>
            <th> 
                <p class="text-white">Уровень</p>
            </th>
            <th>
                <p class="text-white">Действия</p>
            </th>
        </tr>
    </thead>
    <tbody id="PersonListGridContent">
        @foreach(Area area in Model)
        {
            <tr>
                <td><p class="text-white">@area.Name</p></td>
                <td><p class="text-white">@area.Description</p></td>
                <td><p class="text-white">@area.Level</p></td>
                <td>
                    <button type="button" class="btn btn-outline-danger" data-handler="AreaListPartial" data-toggle="ajax-modal-delete-person" data-id="@area.Id" data-url="@Url.Page("Edit", "AreaModalDeletePartial")">
                        Удалить
                    </button>
                    <button type="button" class="btn btn-outline-danger" data-handler="AreaListPartial" data-toggle="ajax-modal-edit-person" data-id="@area.Id" data-url="@Url.Page("Edit", "AreaModalEditPartial")">
                        Редактировать
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>

Diploma — копия/Pages/Shared/_AreaModalPartial.cshtml
@using Diploma.Models;

@*// Pages/Shared/_PersonModalPartial.cshtml*@
@model Area
<!-- Modal -->
<div class="modal fade" id="add-contact" tabindex="-1" role="dialog" aria-labelledby="addContactLabel" aria-hidden="true" style="backdrop-filter: blur(0.6rem);  box-shadow: 1.3rem 1.3rem 1.3rem rgba(0,0,0,0.5); background-color: rgba(255,255,255,0.05) !important;">
    <div class="modal-dialog" role="document">
        <div class="modal-content rounded-3 bg-black">
            <div class="modal-header">
                <h5 class="modal-title text-white" id="addContactLabel">Add contact</h5>
            </div>
            <div class="modal-body">
                <form asp-page-handler="AreaModalPartial">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
                    <input asp-for="Id" class="form-control" type="hidden">
                    <div class="row mb-3">
                        <div class="col-lg-6">
                            <label asp-for="Name" class="col-form-label text-white"></label>
                            <input asp-for="Name" class="form-control">
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="col-lg-6">
                            <label asp-for="Description" class="col-form-label text-white"></label>
                            <input asp-for="Description" class="form-control"/>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label asp-for="Level" class="col-form-label text-white"></label>
                                <input asp-for="Level" type="number" class="form-control" />
                                <span asp-validation-for="Level" class="text-danger"></span>
                            </div>
                            @*<label asp-for="Area" class="col-form-label text-white"></label>
                            <select asp-for="Area" class="form-select" aria-label="Default select example" id="SubCategoryMenu">
                                @*<option value="1">One</option>
                                <option value="2">Two</option>
                                <option value="3">Three</option>*@
                            @*</select>*@

                        </div>

                        
                        
                    </div>

                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                <button type="button" class="btn btn-primary" data-listid="AreaListPartialView" data-handler="AreaListPartial" data-save="modal">Сохранить</button>
            </div>
        </div>
    </div>
</div>

Diploma — копия/Pages/Shared/_CameraDeleteWarningPartial.cshtml
@model int

<div class="modal fade" id="add-contact" tabindex="-1" role="dialog" aria-labelledby="addContactLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content rounded-3 bg-black">
            <div class="modal-header">
                <h5 class="modal-title text-white" id="addContactLabel">Вы уверены что хотите удалить запись?</h5>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-listid="CameraListPartialView" data-handler="CameraListPartial" data-delete="modal" data-id="@Model" data-url="@Url.Page("Edit", "CameraModalDeletePartial")">
                    Удалить
                </button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
            </div>
        </div>
    </div>
</div>

Diploma — копия/Pages/Shared/_CameraListPartial.cshtml
@using Diploma.Models;

@model List<Camera>

<table id="GridPartialView" class="table table-striped GridPartialView">
    <thead>
        <tr>
            <th> 
                <p class="text-white">Имя</p>
            </th>
            <th> 
                <p class="text-white">Область</p>
            </th>
            <th> 
                <p class="text-white">Описание</p>
            </th>
            <th>
                <p class="text-white">Действия</p>
            </th>
        </tr>
    </thead>
    <tbody id="CameraListGridContent">
        @foreach(Camera cam in Model)
        {
            <tr>
                <td><p class="text-white">@cam.Name</p></td>
                <td><p class="text-white">@cam.Area</p></td>
                <td><p class="text-white">@cam.Description</p></td>
                <td>
                    <button type="button" class="btn btn-outline-danger" data-toggle="ajax-modal-delete-person" data-id="@cam.Id" data-url="@Url.Page("Edit", "CameraModalDeletePartial")">
                        Удалить
                    </button>
                    <button type="button" class="btn btn-outline-danger" data-toggle="ajax-modal-edit-person" data-id="@cam.Id" data-url="@Url.Page("Edit", "CameraModalEditPartial")">
                        Редактировать
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>

Diploma — копия/Pages/Shared/_CameraModalPartial.cshtml
@using Diploma.Models;

@*// Pages/Shared/_PersonModalPartial.cshtml*@
@model Camera
<!-- Modal -->
<div class="modal fade" id="add-contact" tabindex="-1" role="dialog" aria-labelledby="addContactLabel" aria-hidden="true" style="backdrop-filter: blur(0.6rem);  box-shadow: 1.3rem 1.3rem 1.3rem rgba(0,0,0,0.5); background-color: rgba(255,255,255,0.05) !important;">
    <div class="modal-dialog" role="document">
        <div class="modal-content rounded-3 bg-black">
            <div class="modal-header">
                <h5 class="modal-title text-white" id="addContactLabel">Add contact</h5>
            </div>
            <div class="modal-body">
                <form asp-page-handler="CameraModalPartial">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
                    <input asp-for="Id" class="form-control" type="hidden">
                    <div class="row mb-3">
                        <div class="col-lg-6">
                            <label asp-for="Name" class="col-form-label text-white"></label>
                            <input asp-for="Name" class="form-control">
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="col-lg-6">
                            <label asp-for="Description" class="col-form-label text-white"></label>
                            <input asp-for="Description" type="email" class="form-control"/>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-lg-6">
                            <label asp-for="Area" class="col-form-label text-white"></label>
                            <select asp-for="Area" class="form-select" aria-label="Default select example" id="SubCategoryMenu">
                                @*<option value="1">One</option>
                                <option value="2">Two</option>
                                <option value="3">Three</option>*@
                            </select>
                            <span asp-validation-for="Area" class="text-danger"></span>
                            
                        </div>
                        @*<h4>Categories</h4>
                        <select asp-for="CategoryId" asp-items="Model.Categories">
                            <option value="">Select Category</option>
                        </select>
                        <h4>SubCategories</h4>
                        <select asp-for="SubCategoryId"></select>*@
                        
                        @*<div class="col-lg-6">
                            <div class="form-group">
                                <label asp-for="Phone" class="col-form-label text-white"></label>
                                <input asp-for="Phone" type="number" class="form-control"/>
                                <span asp-validation-for="Phone" class="text-danger"></span>
                            </div>
                        </div>*@
                    </div>

                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                <button type="button" class="btn btn-primary" data-listid="CameraListPartialView" data-handler="CameraListPartial" data-save="modal">Сохранить</button>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
        $.getJSON(`Edit?handler=Areas`, (data) => {
            $.each(data, function (i, item) {
                $("#SubCategoryMenu").append(`<option value="${item.Id}">${item.Name}</option>`);
            });
        });
        //$("#CategoryId").on("change", function () {
        //    var categoryId = $(this).val();
        //    $("#SubCategoryId").empty();
        //    $("#SubCategoryId").append("<option value=''>Select SubCategory</option>");
            
        //});
    });
</script>

Diploma — копия/Pages/Shared/_PersonDeleteWarningPartial.cshtml
@model int

<div class="modal fade" id="add-contact" tabindex="-1" role="dialog" aria-labelledby="addContactLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content rounded-3 bg-black">
            <div class="modal-header">
                <h5 class="modal-title text-white" id="addContactLabel">Вы уверены что хотите удалить запись?</h5>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-listid="PersonListPartialView" data-handler="PersonListPartial" data-delete="modal" data-id="@Model" data-url="@Url.Page("Edit", "PersonModalDeletePartial")">
                    Удалить
                </button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
            </div>
        </div>
    </div>
</div>

Diploma — копия/Pages/Shared/_PersonListPartial.cshtml
@using Diploma.Models;

@model List<Person>

<table id="GridPartialView" class="table table-striped GridPartialView">
    <thead>
        <tr>
            <th> 
                <p class="text-white">Имя</p>
            </th>
            <th> 
                <p class="text-white">Фамилия</p>
            </th>
            <th> 
                <p class="text-white">Email</p>
            </th>
            <th>
                <p class="text-white">Действия</p>
            </th>
        </tr>
    </thead>
    <tbody id="PersonListGridContent">
        @foreach(Person person in Model)
        {
            <tr>
                <td><p class="text-white">@person.FirstName</p></td>
                <td><p class="text-white">@person.LastName</p></td>
                <td><p class="text-white">@person.Email</p></td>
                <td>
                    <button type="button" class="btn btn-outline-danger" data-handler="PersonListPartial" data-toggle="ajax-modal-delete-person" data-id="@person.Id" data-url="@Url.Page("Edit", "PersonModalDeletePartial")">
                        Удалить
                    </button>
                    <button type="button" class="btn btn-outline-danger" data-handler="PersonListPartial" data-toggle="ajax-modal-edit-person" data-id="@person.Id" data-url="@Url.Page("Edit", "PersonModalEditPartial")">
                        Редактировать
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>

Diploma — копия/Pages/Shared/_PersonModalPartial.cshtml
@using Diploma.Models;

@*// Pages/Shared/_PersonModalPartial.cshtml*@
@model Person
<!-- Modal -->
<div class="modal fade" id="add-contact" tabindex="-1" role="dialog" aria-labelledby="addContactLabel" aria-hidden="true" style="backdrop-filter: blur(0.6rem);  box-shadow: 1.3rem 1.3rem 1.3rem rgba(0,0,0,0.5); background-color: rgba(255,255,255,0.05) !important;">
    <div class="modal-dialog" role="document">
        <div class="modal-content rounded-3 bg-black">
            <div class="modal-header">
                <h5 class="modal-title text-white" id="addContactLabel">Add contact</h5>
            </div>
            <div class="modal-body">
                <form asp-page-handler="PersonModalPartial">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
                    <input asp-for="Id" class="form-control" type="hidden">
                    <div class="row mb-3">
                        <div class="col-lg-6">
                            <label asp-for="FirstName" class="col-form-label text-white"></label>
                            <input asp-for="FirstName" class="form-control">
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                        </div>
                        <div class="col-lg-6">
                            <label asp-for="Email" class="col-form-label text-white"></label>
                            <input asp-for="Email" type="email" class="form-control"/>
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-lg-6">
                            <label asp-for="LastName" class="col-form-label text-white"></label>
                            <input asp-for="LastName" class="form-control">
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label asp-for="Phone" class="col-form-label text-white"></label>
                                <input asp-for="Phone" type="number" class="form-control"/>
                                <span asp-validation-for="Phone" class="text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-lg-6">
                            <label asp-for="Patronymic" class="col-sm-2 col-form-label text-white"></label>
                            <input asp-for="Patronymic" type="text" class="form-control">
                            <span asp-validation-for="Patronymic" class="text-danger"></span>
                        </div>
                        <div class="col-lg-6">
                            <label asp-for="Age" class="col-form-label text-white"></label>
                            <input asp-for="Age" type="number" class="form-control">
                            <span asp-validation-for="Patronymic" class="text-danger"></span>
                        </div>
                    </div>
                    <fieldset class="row mb-3">
                        <legend class="col-form-label col-sm-2 pt-0 text-white">Пол</legend>
                        <div class="col-sm-10">
                            <div class="form-check">
                                <input asp-for="Gender" class=" form-check-input" type="radio" id="gridRadios1" value="Male" checked>
                                <label class="form-check-label text-white" for="gridRadios1">
                                    Мужской
                                </label>
                            </div>
                            <div class="form-check">
                                <input asp-for="Gender" class="form-check-input" type="radio" id="gridRadios2" value="Female">
                                <label class="form-check-label text-white" for="gridRadios2">
                                    Женский
                                </label>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                <button type="button" class="btn btn-primary" data-handler="PersonListPartial" data-listid="PersonListPartialView" data-save="modal">Сохранить</button>
            </div>
        </div>
    </div>
</div>

Diploma — копия/Pages/Shared/_UserListPartial.cshtml
@using Diploma.Models;
@using Microsoft.AspNetCore.Identity;

@model List<IdentityUser>

<table id="GridPartialView" class="table table-striped GridPartialView">
    <thead>
        <tr>
            <th> 
                <p class="text-white">Id</p>
            </th>
            <th> 
                <p class="text-white">Имя пользователя</p>
            </th>
            <th> 
                <p class="text-white">Email</p>
            </th>
            <th>
                <p class="text-white">Номер телефона</p>
            </th>
            <th>
                <p class="text-white">Количество неправильных входов</p>
            </th>
            <th>
                <p class="text-white">Действия</p>
            </th>
        </tr>
    </thead>
    <tbody id="UserListGridContent">
        @foreach(IdentityUser user in Model)
        {
            <tr>
                <td><p class="text-white">@user.Id</p></td>
                <td><p class="text-white">@user.UserName</p></td>
                <td><p class="text-white">@user.Email</p></td>
                <td><p class="text-white">@user.PhoneNumber</p></td>
                <td><p class="text-white">@user.AccessFailedCount</p></td>
                
                <td>
                    <button type="button" class="btn btn-outline-danger" data-handler="UserListPartial" data-toggle="ajax-modal-delete-person" data-id="@user.Id" data-url="@Url.Page("Edit", "UserModalDeletePartial")">
                        Удалить
                    </button>
                    <button type="button" class="btn btn-outline-danger" data-handler="UserListPartial" data-toggle="ajax-modal-edit-person" data-id="@user.Id" data-url="@Url.Page("Edit", "UserModalEditPartial")">
                        Редактировать
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>